### ISSUE TITLE
[BUG] Extenstion stopped recognizing commitlint rules

### ISSUE THREAD

**Issue by avendiart** [vivaxy/vscode-conventional-commits#102]
**Describe the bug**
Since yesterday the extension stopped recognizing configured scopes and other settings for me and my colleagues. Unfortunately I have no idea why, nothing has changed about the setup of the repository or the configurations themselves. Have there been any recent changes to the extensions which may have caused it? The last working version for us seems to be `1.16.1`.

**Application logs**
```
Activated
vscode.env.language: en
[warning] getNLS: Missing translation for en
Started
VSCode version: 1.54.3
VSCode Conventional Commits version: 1.18.0
Git version: 1.0.0
autoCommit: true
gitmoji: false
emojiFormat: code
scopes: 
lineBreak: 
promptScopes: true
git.enableSmartCommit: true
git.smartCommitChanges: all
git.postCommitCommand: none
arg: undefined
git.repositories: /home/redacted
workspaceFolders: /home/redacted
commitlintRuleConfigs: {}
```

**Comment by yi-Xu-0100** [comment]
👋 @avendiart I make some changes about the scope, which may be led to the issue, Could you give the `commitlint rules` also?

**Comment by yi-Xu-0100** [comment]
@vivaxy after the webpack, the `commitlint` can not load the rules from `node_modules`. But the path is right.

https://github.com/vivaxy/vscode-conventional-commits/blob/4dacf436feba57fe17e40ba0c1c34c002ab43cab/src/lib/commitlint.ts#L14-L22

I try to add an output for the error.
```
appendLine(`[warning]: ${e.message}`);
```
and it shows the right path for the module.

```bash
[warning]: Cannot find module 'c:\Users\xxxx\Desktop\test\vscode-conventional-commits\node_modules\@commitlint\config-conventional\index.js'
commitlintRuleConfigs: {}
```

I don't know why it happened, any suggestion about it? 😅

**Comment by vivaxy** [comment]
@yi-Xu-0100 

The error is:

```
Error: Cannot find module '/Users/xxx/Developer/test/node_modules/@commitlint/config-conventional/index.js'
    at webpackEmptyContext (/Users/xxx/Developer/github/vscode-conventional-commits/node_modules/@commitlint/resolve-extends/lib|sync:2:1)
    at /Users/xxx/Developer/github/vscode-conventional-commits/node_modules/@commitlint/resolve-extends/lib/index.js:42:1
    at Array.reduce (<anonymous>)
    at loadExtends (/Users/xxx/Developer/github/vscode-conventional-commits/node_modules/@commitlint/resolve-extends/lib/index.js:39:1)
    at Object.resolveExtends [as default] (/Users/xxx/Developer/github/vscode-conventional-commits/node_modules/@commitlint/resolve-extends/lib/index.js:25:1)
    at Object.load [as default] (/Users/xxx/Developer/github/vscode-conventional-commits/node_modules/@commitlint/load/lib/load.js:38:1) {code: 'MODULE_NOT_FOUND', stack: 'Error: Cannot find module '/Users/xxx/Deve…de_modules/@commitlint/load/lib/load.js:38:1)', message: 'Cannot find module '/Users/xxx/Developer/…es/@commitlint/config-conventional/index.js''}
```

```js
    return ext.reduce((configs, raw) => {
        const load = context.require || require;
        const resolved = resolveConfig(raw, context);
        const c = load(resolved);
        const cwd = path_1.default.dirname(resolved);
        const ctx = merge_1.default({}, context, { cwd });
```

I think it's because `@commitlint/resolve-extends` uses `require`, but after webpack bundled, `require` is process by webpack.

**Comment by avendiart** [comment]
@yi-Xu-0100 Nothing fancy:
```js
module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'header-max-length': [2, 'always', 140],
    'scope-empty': [2, 'never'],
    'scope-enum': [2, 'always', ['web', 'app']],
  },
};
```

**Comment by yi-Xu-0100** [comment]
@avendiart I make a quick patch for this issue, maybe my solution is not the best way to fix it, but it will work in the beta version - [vscode-conventional-commits-84beb69.vsix](https://github.com/vivaxy/vscode-conventional-commits/suites/2338775999/artifacts/49344920). 😅

I think the extension webpacked is faster than before! Please tell me if there is any problem about it! Thanks! 😁

**Comment by yi-Xu-0100** [comment]
@avendiart I make a mistake to make the above beta extension can read the rules but not work. 🤪

I fix the bug and build a new beta version - [vscode-conventional-commits-fbf399f.vsix](https://github.com/vivaxy/vscode-conventional-commits/suites/2338906350/artifacts/49349833). Try to use it! (I have test in locally this time.) 😅

**Comment by avendiart** [comment]
@yi-Xu-0100 still doesn't work for me with `1.18.1-fbf399f`, rules aren't loaded. In the output logs I also see `[warning]: The "path" argument must be of type string. Received undefined`

**Comment by yi-Xu-0100** [comment]
@avendiart I test well with the same configuration with the latest extension in windows. 😅

Could you test the beta version - [vscode-conventional-commits-88f5531.vsix](https://github.com/vivaxy/vscode-conventional-commits/suites/2341626614/artifacts/49425001)? This version improves the log output. 😀

**Comment by vivaxy** [comment]
> @avendiart I test well with the same configuration with the latest extension in windows. 😅
> 
> Could you test the beta version - [vscode-conventional-commits-88f5531.vsix](https://github.com/vivaxy/vscode-conventional-commits/suites/2341626614/artifacts/49425001)? This version improves the log output. 😀

Confirmed, this version works well in MacOS.

**Comment by avendiart** [comment]
Still the same issue:

```
[error] commitlint: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
	at validateString (internal/validators.js:120:11)
	at Object.dirname (path.js:1128:5)
	at module.exports (/home/user/.vscode-server/extensions/vivaxy.vscode-conventional-commits-1.18.2-88f5531/dist/extension.js:21951:37)
	at loadJs (/home/user/.vscode-server/extensions/vivaxy.vscode-conventional-commits-1.18.2-88f5531/dist/extension.js:2679:18)
	at Explorer.loadFileContent (/home/user/.vscode-server/extensions/vivaxy.vscode-conventional-commits-1.18.2-88f5531/dist/extension.js:2140:32)
	at Explorer.createCosmiconfigResult (/home/user/.vscode-server/extensions/vivaxy.vscode-conventional-commits-1.18.2-88f5531/dist/extension.js:2145:36)
	at Explorer.loadSearchPlace (/home/user/.vscode-server/extensions/vivaxy.vscode-conventional-commits-1.18.2-88f5531/dist/extension.js:2126:31)
	at async Explorer.searchDirectory (/home/user/.vscode-server/extensions/vivaxy.vscode-conventional-commits-1.18.2-88f5531/dist/extension.js:2111:27)
	at async run (/home/user/.vscode-server/extensions/vivaxy.vscode-conventional-commits-1.18.2-88f5531/dist/extension.js:2091:22)
	at async cacheWrapper (/home/user/.vscode-server/extensions/vivaxy.vscode-conventional-commits-1.18.2-88f5531/dist/extension.js:2471:18)
	at async Explorer.search (/home/user/.vscode-server/extensions/vivaxy.vscode-conventional-commits-1.18.2-88f5531/dist/extension.js:2083:20)
	at async Object.loadConfig (/home/user/.vscode-server/extensions/vivaxy.vscode-conventional-commits-1.18.2-88f5531/dist/extension.js:1851:19)
	at async Object.load [as default] (/home/user/.vscode-server/extensions/vivaxy.vscode-conventional-commits-1.18.2-88f5531/dist/extension.js:21612:18)
[info] commitlintRuleConfigs:
{}
```

**Comment by yi-Xu-0100** [comment]
@avendiart Is the `cwd` path as same as `workspaceFolders` to the repository path?

**Comment by avendiart** [comment]
Yes. And yes, the extension installed within a WSL2 distribution for me if that helps.

**Comment by yi-Xu-0100** [comment]
@avendiart Try to use the beta version - [vscode-conventional-commits-a07b5d9.vsix](https://github.com/vivaxy/vscode-conventional-commits/suites/2356268356/artifacts/49861486)! 😅

I test well in my VS Code remote! 😁
